spring:
  application:
    name: franchise-api
  main:
    web-application-type: reactive

  r2dbc:
    url: r2dbc:mysql://localhost:3306/franchise?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: Felix2903

  flyway:
    enabled: true
    url: jdbc:mysql://localhost:3306/franchise?allowPublicKeyRetrieval=true&useSSL=false
    user: root
    password: Felix2903
    baseline-on-migrate: true
    locations: classpath:db/migration

  webflux:
    base-path: /api/v1

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,loggers,info

app:
  cors:
    enabled: true
    allowed-origins: "http://localhost:4200,http://localhost:3000"
    allowed-methods: "GET,POST,PATCH,DELETE,OPTIONS"
    allowed-headers: "*"
    allow-credentials: true